CREATE OR REPLACE DYNAMIC TABLE COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
  TARGET_LAG = '1 hour'
  WAREHOUSE = COCO_WORKSHOP_WH
AS
SELECT
    MD5(SOURCE_SYSTEM || '|' || INVOICE_ID) AS INVOICE_SK,
    SOURCE_SYSTEM,
    INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    VENDOR_NAME,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    CURRENCY_CODE,
    PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    COST_CENTER,
    APPROVAL_STATUS,
    CREATED_AT
FROM (
    -- SAP (unchanged)
    SELECT
        'SAP' AS SOURCE_SYSTEM,
        INVOICE_ID, INVOICE_NUMBER, VENDOR_ID, VENDOR_NAME,
        INVOICE_DATE, DUE_DATE, INVOICE_AMOUNT, CURRENCY_CODE,
        PAYMENT_TERMS, PO_NUMBER, LINE_DESCRIPTION, GL_ACCOUNT,
        COST_CENTER, APPROVAL_STATUS, CREATED_AT
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_SAP_AP_INVOICES

    UNION ALL

    -- Oracle (unchanged)
    SELECT
        'ORACLE' AS SOURCE_SYSTEM,
        INV_ID, INV_NUM, SUPPLIER_ID, SUPPLIER_NAME,
        INV_DATE, PAYMENT_DUE_DATE, TOTAL_AMOUNT, CURRENCY,
        CASE TERMS_CODE WHEN 'N30' THEN 'NET30' WHEN 'N60' THEN 'NET60' ELSE TERMS_CODE END,
        PURCHASE_ORDER, DESCRIPTION, ACCOUNT_CODE,
        DEPT_CODE,
        CASE STATUS WHEN 'VALIDATED' THEN 'APPROVED' ELSE STATUS END,
        CREATION_DATE
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_ORACLE_AP_INVOICES

    UNION ALL

    -- Baan (NEW — with dedup per BR-003)
    SELECT
        'BAAN' AS SOURCE_SYSTEM,
        BAN_INVOICE_ID,
        BAN_INVOICE_REF,
        BAN_VENDOR_CODE,
        BAN_VENDOR_DESC,
        BAN_INV_DATE,
        BAN_PAY_DATE,
        BAN_AMOUNT,
        BAN_CURR,
        BAN_PAY_TERMS,
        BAN_PO_REF,
        BAN_LINE_DESC,
        BAN_GL_CODE,
        BAN_COST_CTR,
        CASE BAN_STATUS
            WHEN 'POSTED' THEN 'APPROVED'
            WHEN 'APPROVED' THEN 'APPROVED'
            WHEN 'PENDING' THEN 'PENDING'
            ELSE BAN_STATUS
        END,
        BAN_CREATED
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_BAAN_AP_INVOICES
    QUALIFY ROW_NUMBER() OVER (PARTITION BY BAN_INVOICE_REF ORDER BY BAN_CREATED DESC) = 1

    UNION ALL

    -- Workday (NEW)
    SELECT
        'WORKDAY' AS SOURCE_SYSTEM,
        WD_INVOICE_ID,
        WD_INVOICE_NUM,
        WD_SUPPLIER_ID,
        WD_SUPPLIER_NAME,
        WD_INVOICE_DATE,
        WD_DUE_DATE,
        WD_AMOUNT,
        WD_CURRENCY,
        WD_PAY_TERMS,
        WD_PO_NUMBER,
        WD_MEMO,
        WD_LEDGER_ACCOUNT,
        WD_COST_CENTER,
        CASE WD_APPROVAL_STATUS
            WHEN 'Approved' THEN 'APPROVED'
            WHEN 'In Review' THEN 'PENDING'
            ELSE UPPER(WD_APPROVAL_STATUS)
        END,
        WD_CREATED_DATE
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_WORKDAY_AP_INVOICES
);
